var annotated_dup =
[
    [ "BelongsTo", "class_belongs_to.html", "class_belongs_to" ],
    [ "DataMapper", "class_data_mapper.html", "class_data_mapper" ],
    [ "Field", "struct_field.html", "struct_field" ],
    [ "HasMany", "class_has_many.html", "class_has_many" ],
    [ "HasManyThrough", "class_has_many_through.html", "class_has_many_through" ],
    [ "HasOneThrough", "class_has_one_through.html", "class_has_one_through" ],
    [ "SqlAlterTableQueryBuilder", "class_sql_alter_table_query_builder.html", null ],
    [ "SqlConnection", "class_sql_connection.html", "class_sql_connection" ],
    [ "SqlConnectionDataSource", "struct_sql_connection_data_source.html", null ],
    [ "SqlConnectionString", "struct_sql_connection_string.html", null ],
    [ "SqlCreateTableQueryBuilder", "class_sql_create_table_query_builder.html", null ],
    [ "SqlDeleteQueryBuilder", "class_sql_delete_query_builder.html", null ],
    [ "SqlErrorInfo", "struct_sql_error_info.html", null ],
    [ "SqlInsertQueryBuilder", "class_sql_insert_query_builder.html", null ],
    [ "SqlJoinConditionBuilder", "class_sql_join_condition_builder.html", null ],
    [ "SqlLogger", "class_sql_logger.html", "class_sql_logger" ],
    [ "SqlMigrationQueryBuilder", "class_sql_migration_query_builder.html", null ],
    [ "SqlQualifiedTableColumnName", "struct_sql_qualified_table_column_name.html", null ],
    [ "SqlQueryBuilder", "class_sql_query_builder.html", "class_sql_query_builder" ],
    [ "SqlQueryFormatter", "class_sql_query_formatter.html", "class_sql_query_formatter" ],
    [ "SqlRealName", "struct_sql_real_name.html", null ],
    [ "SqlRequireLoadedError", "class_sql_require_loaded_error.html", null ],
    [ "SqlResultCursor", "class_sql_result_cursor.html", "class_sql_result_cursor" ],
    [ "SqlRowIterator", "class_sql_row_iterator.html", null ],
    [ "SqlScopedTraceLogger", "class_sql_scoped_trace_logger.html", null ],
    [ "SqlSelectQueryBuilder", "class_sql_select_query_builder.html", "class_sql_select_query_builder" ],
    [ "SqlStatement", "class_sql_statement.html", "class_sql_statement" ],
    [ "SqlUpdateQueryBuilder", "class_sql_update_query_builder.html", null ],
    [ "SqlWildcardType", "struct_sql_wildcard_type.html", null ]
];