Lightweight: DataMapper Class Reference
DataMapper Class Reference
Data Mapper
Main API for mapping records to and from the database using high level C++ syntax.
#include <DataMapper.hpp>
Public Member Functions
DataMapper ()
Constructs a new data mapper, using the default connection.
DataMapper (SqlConnection &&connection)
Constructs a new data mapper, using the given connection.
DataMapper (DataMapper const &)=delete
DataMapper (DataMapper &&) noexcept=default
DataMapper & operator= (DataMapper const &)=delete
DataMapper & operator= (DataMapper &&) noexcept=default
SqlConnection const & Connection () const noexcept
Returns the connection reference used by this data mapper.
SqlConnection & Connection () noexcept
Returns the mutable connection reference used by this data mapper.
template<typename Record >
std::vector< std::string > CreateTableString (SqlServerType serverType)
Constructs a string list of SQL queries to create the table for the given record type.
template<typename FirstRecord , typename... MoreRecords>
std::vector< std::string > CreateTablesString (SqlServerType serverType)
Constructs a string list of SQL queries to create the tables for the given record types.
template<typename Record >
void CreateTable ()
Creates the table for the given record type.
template<typename FirstRecord , typename... MoreRecords>
void CreateTables ()
Creates the tables for the given record types.
template<typename Record >
RecordId Create (Record &record)
Creates a new record in the database.
template<typename Record >
RecordId CreateExplicit (Record const &record)
Creates a new record in the database.
template<typename Record , typename... Args>
std::optional< Record > QuerySingle (SqlSelectQueryBuilder selectQuery, Args &&... args)
template<typename Record , typename... PrimaryKeyTypes>
std::optional< Record > QuerySingle (PrimaryKeyTypes &&... primaryKeys)
Queries a single record (based on primary key) from the database.
template<typename Record , typename... InputParameters>
std::vector< Record > Query (SqlSelectQueryBuilder::ComposedQuery const &selectQuery, InputParameters &&... inputParameters)
Queries multiple records from the database, based on the given query.
template<typename Record , typename... InputParameters>
std::vector< Record > Query (std::string_view sqlQueryString, InputParameters &&... inputParameters)
Queries multiple records from the database, based on the given query.
template<typename Record >
bool IsModified (Record const &record) const noexcept
Checks if the record has any modified fields.
template<typename Record >
void Update (Record &record)
Updates the record in the database.
template<typename Record >
std::size_t Delete (Record const &record)
Deletes the record from the database.
template<typename Record >
std::size_t Count ()
Counts the total number of records in the database for the given record type.
template<typename Record >
std::vector< Record > All ()
Loads all records from the database for the given record type.
template<typename Record >
std::optional< Record > Find (RecordId id)
Finds a record by its primary key.
template<typename Record , typename ColumnName , typename T >
std::optional< Record > FindBy (ColumnName const &columnName, T const &value)
Finds a record by the given column name and value.
template<typename Record >
auto Query () -> SqlQueryBuilder
Constructs an SQL query builder for the given record type.
SqlQueryBuilder FromTable (std::string_view tableName)
Constructs an SQL query builder for the given table name.
template<typename Record >
void ClearModifiedState (Record &record) noexcept
Clears the modified state of the record.
template<typename Record >
void LoadRelations (Record &record)
Loads all direct relations to this record.
template<typename Record >
decltype(auto) GetPrimaryKeyField (Record const &record) const
Returns the first primary key field of the record.
template<typename Record >
void ConfigureRelationAutoLoading (Record &record)
template<typename Record , typename... InputParameters>
LIGHTWEIGHT_FORCE_INLINE std::vector< Record > Query (SqlSelectQueryBuilder::ComposedQuery const &selectQuery, InputParameters &&... inputParameters)
template<typename Record >
LIGHTWEIGHT_FORCE_INLINE decltype(auto) GetPrimaryKeyField (Record const &record) const
template<typename Record , typename ValueType >
LIGHTWEIGHT_FORCE_INLINE void SetId (Record &record, ValueType &&id)
template<typename Record >
LIGHTWEIGHT_FORCE_INLINE void BindOutputColumns (Record &record)
Static Public Member Functions
template<typename Record >
static std::string Inspect (Record const &record)
Constructs a human readable string representation of the given record.
Detailed Description
Main API for mapping records to and from the database using high level C++ syntax.
See also
Field, BelongsTo, HasMany, HasManyThrough, HasOneThrough
Definition at line 73 of file DataMapper.hpp.
Constructor & Destructor Documentation
DataMapper() [1/2]
DataMapper::DataMapper () inline
Constructs a new data mapper, using the default connection.
Definition at line 77 of file DataMapper.hpp.
DataMapper() [2/2]
DataMapper::DataMapper (SqlConnection && connection) inline explicit
Constructs a new data mapper, using the given connection.
Definition at line 84 of file DataMapper.hpp.
Member Function Documentation
Connection() [1/2]
SqlConnection const & DataMapper::Connection () const inline noexcept
Returns the connection reference used by this data mapper.
Definition at line 97 of file DataMapper.hpp.
Connection() [2/2]
SqlConnection & DataMapper::Connection () inline noexcept
Returns the mutable connection reference used by this data mapper.
Definition at line 103 of file DataMapper.hpp.
Inspect()
template<typename Record > std::string DataMapper::Inspect (Record const & record) static
Constructs a human readable string representation of the given record.
Definition at line 265 of file DataMapper.hpp.
CreateTableString()
template<typename Record > std::vector< std::string > DataMapper::CreateTableString (SqlServerType serverType)
Constructs a string list of SQL queries to create the table for the given record type.
Definition at line 325 of file DataMapper.hpp.
References SqlQueryFormatter::Get(), and SqlQueryBuilder::Migration().
CreateTablesString()
template<typename FirstRecord , typename... MoreRecords> std::vector< std::string > DataMapper::CreateTablesString (SqlServerType serverType)
Constructs a string list of SQL queries to create the tables for the given record types.
Definition at line 378 of file DataMapper.hpp.
CreateTable()
template<typename Record > void DataMapper::CreateTable ()
Creates the table for the given record type.
Definition at line 390 of file DataMapper.hpp.
References SqlStatement::ExecuteDirect(), and SqlConnection::ServerType().
CreateTables()
template<typename FirstRecord , typename... MoreRecords> void DataMapper::CreateTables ()
Creates the tables for the given record types.
Definition at line 400 of file DataMapper.hpp.
Create()
template<typename Record > RecordId DataMapper::Create (Record & record)
Creates a new record in the database.
The record is inserted into the database and the primary key is set on this record.
Returns
The primary key of the newly created record.
Definition at line 445 of file DataMapper.hpp.
References ClearModifiedState(), ConfigureRelationAutoLoading(), and CreateExplicit().
CreateExplicit()
template<typename Record > RecordId DataMapper::CreateExplicit (Record const & record)
Creates a new record in the database.
Note
This is a variation of the Create() method and does not update the record's primary key.
Returns
The primary key of the newly created record.
Definition at line 416 of file DataMapper.hpp.
References SqlStatement::Execute(), SqlQueryBuilder::Insert(), SqlStatement::LastInsertId(), SqlStatement::Prepare(), and SqlConnection::Query().
Referenced by Create().
QuerySingle() [1/2]
template<typename Record , typename... Args> std::optional< Record > DataMapper::QuerySingle (SqlSelectQueryBuilder selectQuery, Args &&... args)
Definition at line 602 of file DataMapper.hpp.
QuerySingle() [2/2]
template<typename Record , typename... PrimaryKeyTypes> std::optional< Record > DataMapper::QuerySingle (PrimaryKeyTypes &&... primaryKeys)
Queries a single record (based on primary key) from the database.
The primary key(s) are used to identify the record to load. If the record is not found, std::nullopt is returned.
Definition at line 569 of file DataMapper.hpp.
References SqlStatement::CloseCursor(), ConfigureRelationAutoLoading(), SqlStatement::Execute(), SqlStatement::FetchRow(), SqlStatement::Prepare(), SqlConnection::Query(), and SqlQueryBuilder::Select().
Query() [1/3]
template<typename Record , typename... InputParameters> std::vector< Record > DataMapper::Query (std::string_view sqlQueryString, InputParameters &&... inputParameters)
Queries multiple records from the database, based on the given query.
Definition at line 638 of file DataMapper.hpp.
References ConfigureRelationAutoLoading(), SqlStatement::Execute(), SqlStatement::FetchRow(), and SqlStatement::Prepare().
IsModified()
template<typename Record > bool DataMapper::IsModified (Record const & record) const noexcept
Checks if the record has any modified fields.
Definition at line 485 of file DataMapper.hpp.
Update()
template<typename Record > void DataMapper::Update (Record & record)
Updates the record in the database.
Definition at line 502 of file DataMapper.hpp.
References ClearModifiedState(), SqlStatement::Execute(), SqlStatement::Prepare(), SqlConnection::Query(), and SqlQueryBuilder::Update().
Delete()
template<typename Record > std::size_t DataMapper::Delete (Record const & record)
Deletes the record from the database.
Definition at line 541 of file DataMapper.hpp.
References SqlQueryBuilder::Delete(), SqlStatement::Execute(), SqlStatement::NumRowsAffected(), SqlStatement::Prepare(), and SqlConnection::Query().
Find()
template<typename Record > std::optional< Record > DataMapper::Find (RecordId id)
Finds a record by its primary key.
Parameters
id The primary key of the record to find.
Returns
The record if found, otherwise std::nullopt.
FindBy()
template<typename Record , typename ColumnName , typename T > std::optional< Record > DataMapper::FindBy (ColumnName const & columnName, T const & value)
Finds a record by the given column name and value.
Parameters
columnName The name of the column to search.
value The value to search for.
Returns
The record if found, otherwise std::nullopt.
Query() [2/3]
template<typename Record > auto DataMapper::Query () -> SqlQueryBuilder inline
Constructs an SQL query builder for the given record type.
Definition at line 200 of file DataMapper.hpp.
References SqlConnection::Query().
FromTable()
SqlQueryBuilder DataMapper::FromTable (std::string_view tableName) inline
Constructs an SQL query builder for the given table name.
Definition at line 206 of file DataMapper.hpp.
References SqlConnection::Query().
ClearModifiedState()
template<typename Record > void DataMapper::ClearModifiedState (Record & record) noexcept
Clears the modified state of the record.
Definition at line 663 of file DataMapper.hpp.
Referenced by Create(), and Update().
LoadRelations()
template<typename Record > void DataMapper::LoadRelations (Record & record)
Loads all direct relations to this record.
Definition at line 900 of file DataMapper.hpp.
ConfigureRelationAutoLoading()
template<typename Record > void DataMapper::ConfigureRelationAutoLoading (Record & record)
Configures the auto loading of relations for the given record.
This means, that no explicit loading of relations is required. The relations are automatically loaded when accessed.
Definition at line 985 of file DataMapper.hpp.
References SqlSelectQueryBuilder::All(), SqlStatement::CloseCursor(), ConfigureRelationAutoLoading(), SqlSelectQueryBuilder::Count(), SqlStatement::Execute(), SqlStatement::FetchRow(), SqlStatement::GetColumn(), SqlStatement::Prepare(), HasOneThrough< OtherTable, ThroughTable >::SetAutoLoader(), BelongsTo< TheReferencedField, ColumnNameOverrideString >::SetAutoLoader(), HasMany< OtherRecord >::SetAutoLoader(), and HasManyThrough< ReferencedRecordT, ThroughRecordT >::SetAutoLoader().
Referenced by ConfigureRelationAutoLoading(), Create(), Query(), and QuerySingle().
Query() [3/3]
template<typename Record , typename... InputParameters> LIGHTWEIGHT_FORCE_INLINE std::vector< Record > DataMapper::Query (SqlSelectQueryBuilder::ComposedQuery const & selectQuery, InputParameters &&... inputParameters) inline
Definition at line 629 of file DataMapper.hpp.
GetPrimaryKeyField()
template<typename Record > LIGHTWEIGHT_FORCE_INLINE decltype(auto) DataMapper::GetPrimaryKeyField (Record const & record) const inline
Definition at line 926 of file DataMapper.hpp.
SetId()
template<typename Record , typename ValueType > LIGHTWEIGHT_FORCE_INLINE void DataMapper::SetId (Record & record, ValueType && id) inline
Definition at line 942 of file DataMapper.hpp.
BindOutputColumns()
template<typename Record > LIGHTWEIGHT_FORCE_INLINE void DataMapper::BindOutputColumns (Record & record) inline
Definition at line 959 of file DataMapper.hpp.
The documentation for this class was generated from the following file:
Lightweight/DataMapper/DataMapper.hpp